# Generated by Django 4.2.3 on 2023-07-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityapp.team'),
        ),
    ]
